### ISSUE TITLE
Allow passing oauth configuration instead of using the /.well-known endpoint 

### ISSUE THREAD

**Issue by ludat** [cloudentity/oauth2c#101]
I have a server that supports oauth2 but doesn't have a `/.well-known/openid-configuration`.

I can use it with a lot of libraries by setting the token and  authentication endpoints, and it works, would it be possible for this cli to accept the parameters that it gets from the endpoint via cli arguments?

IIRC that endpoint is only mandatory for oidc, not oauth2.

**Comment by chrisclayson** [comment]
I +1 this request ... I have a similar requirement.

**Comment by mbilski** [comment]
Added in https://github.com/cloudentity/oauth2c/pull/110
