### ISSUE TITLE
Windows binaries

### ISSUE THREAD

**Issue by igitur** [cloudentity/oauth2c#105]
Thanks for a great tool.

Would you consider adding Windows binaries to the Github Releases page? This would enable me to reference it from a [scoop.sh](https://scoop.sh) repository and make installation and updating easy for users who don't have the go compilers and runtime available.

Thanks.

**Comment by mbilski** [comment]
Hi @igitur 

I think we are already releasing window binaries 

<img width="1196" alt="image" src="https://github.com/cloudentity/oauth2c/assets/909896/5c40e730-aaf9-43ff-a575-9f5d3bc282a5">

https://github.com/cloudentity/oauth2c/releases/tag/v1.13.0

Would that work with scoop?

**Comment by igitur** [comment]
Ah, sorry, I'm so used to .tar.gz files being source code packages that I didn't even bother inspecting. 

I submitted a PR for a scoop item now. https://github.com/ScoopInstaller/Main/pull/5720

**Comment by igitur** [comment]
@mbilski I don't know much about ARM, but I see there are 2 Windows ARM releases. Is `arm` for 32bit ARM and `arm64` for 64bit ARM? I think that's the logical assumption, but I just want to make doubly sure.
