### ISSUE TITLE
Redeeming authorization code for token fails in v1.14 (MS Entra - Web Application)

### ISSUE THREAD

**Issue by andoks** [cloudentity/oauth2c#109]
Authenticating using oauth2c when application is configured as "web" in MS Entra fails using v1.14 with the error `AADSTS9002326: Cross-origin token redemption is permitted only for the 'Single-Page Application' client-type. Request origin: 'http://localhost:9876'. Trace ID:...`. 

The same configuration works with v1.13, leading me to believe this is caused by the change introduced in https://github.com/cloudentity/oauth2c/pull/108. I suspect MS Entra errors out if the Origin header is set and the application is of "web" type instead of "single page application" type.

**Comment by mbilski** [comment]
Hi @andoks 

In https://github.com/cloudentity/oauth2c/commit/f6c72a2eb944cbb088fba2c4caae5336120612d0 I'm adding the Origin header only if the auth method is None.

I think this way we can solve both issues without introducing any new flags.

**Comment by andoks** [comment]
Thanks! It seems to have fixed the issue for me :+1:
