### ISSUE TITLE
`authentication_code` support

### ISSUE THREAD

**Issue by timsearle** [cloudentity/oauth2c#116]
Please can you add support for [Cloudentity Passwordless journeys](https://cloudentity.com/developers/app-dev-tutorials/identity-pools/add-passwordless-authentication/) that take an `extended_code` or `code` as an input to the flow.

If this is already supported, please let me know what arguments to use.

**Comment by timsearle** [comment]
@ikawalec any ideas when this might be supported?

**Comment by ikawalec** [comment]
Hi @timsearle this feature has been added: https://github.com/cloudentity/oauth2c/releases/tag/v1.17.0

**Comment by timsearle** [comment]
Thank you!
