### ISSUE TITLE
Homebrew Integration

### ISSUE THREAD

**Issue by bbkane** [cloudentity/oauth2c#23]
Hello!

Could you possible add Homebrew integration (in core or in a homebrew tap) so I can use `brew` to install and update `oauth2c`?

There are different ways to do this, but I personally use [GoReleaser](https://goreleaser.com/) to  generate the Homebrew formula and commit it to my Homebrew tap repo when I push to GitHub.

Docs: [GoReleasor Homebrew Integration](https://goreleaser.com/customization/homebrew/?h=homebrew), [GoReleasor GitHub Actions Integration](https://goreleaser.com/ci/actions/)

See how this works in a small project of mine: See [my .goreleasor](https://github.com/bbkane/fling/blob/f9a2bcec8af054c03cdda6d60e6233fc11b92645/.goreleaser.yml#L34), [my GitHub workflow](https://github.com/bbkane/fling/blob/f9a2bcec8af054c03cdda6d60e6233fc11b92645/.github/workflows/gorelease.yml), and [the generated formula](https://github.com/bbkane/homebrew-tap/blob/83b934d239b105e15f98f70466247d00c4615dab/Formula/fling.rb)

**Comment by mbilski** [comment]
Hello,

sure, I'll add it.

Thanks

**Comment by mbilski** [comment]
Added in #24

**Comment by bbkane** [comment]
Thank you!
