### ISSUE TITLE
Allow configuring audiences

### ISSUE THREAD

**Issue by flokli** [cloudentity/oauth2c#58]
It'd be nice if `oauth2c` would support specifying the [Audience in Authorization Code, Implicit, and hybrid flows](https://www.ory.sh/docs/hydra/guides/audiences#audience-in-authorization-code-implicit-and-hybrid-flows) (`audience` URL parameter):

> When performing an OAuth 2.0 Authorization Code Grant, Implicit Grant, or hybrid flow, developers can request audiences at the /oauth2/auth endpoint using the audience query parameter:

```
https://{project.slug}.projects.oryapis.com/oauth2/auth
  ?client_id=...
  &scope=...
  &audience=https://api.my-cloud.com/user+https://some-tenant.my-cloud.com/
```

> The audience query parameter can contain multiple strings separated by a URL-encoded space (+ or %20). The audience values must also be URL-encoded.

**Comment by mbilski** [comment]
Done in #60
