### ISSUE TITLE
Proxy settings aren't respected

### ISSUE THREAD

**Issue by brandon-gibbs** [cloudentity/oauth2c#62]
I'm trying to use this tool in an environment where all traffic is routed via a proxy, but this tool doesn't seem to use HTTP_PROXY or HTTPS_PROXY environment variables.

Any suggestions or enhancements that need to be made? All my requests timeout as it won't get through the proxy. Thanks.

**Comment by mbilski** [comment]
Thanks for reporting this. I added support for HTTP_PROXY in #63 and released it as v1.9.0
