### ISSUE TITLE
When using authorization code flow --signing-key parameter is ignored.

### ISSUE THREAD

**Issue by Te0** [cloudentity/oauth2c#70]
When using oauth2c to trigger an authorization code flow, the --signing-key parameter is not used, the jwks_endpoint from the server openid-configuration is always used.

This is causing problems when the issuer is exposing a set of keys where some of them are not compatible with go-jose.

**Comment by mbilski** [comment]
Hi @Te0 

the `--signing-key` flag is used to specify the private signing key for jwt bearer grant type, dpop, signing request object and/or private key jwt authentication method.

Could you provide more context and an example of such key that is not compatible with go-jose?

The only place where the signing key from jwks endpoint is used is the JARM. Is that you use case?

Would adding a flag like `--jwks-signing-key-id` work for you?

**Comment by Te0** [comment]
Hello,

Thanks for getting back, I will try to give some more context!

I am trying to go through an authorization code flow with an issuer. The issuer is exposing a bunch of keys from the jwks endpoint. I am only interested in one of all these keys for my flow, the RS512 key.

When I initiate the authorization code flow and the httpServer is started in the callback/background process, it exits unexpectedly because it fails to parse one of the keys in the list of jwks that the issuer is returning. This key is an EC key and not a key I am interested in for my auth code flow.

This is the error before the process exits:

`ERROR   failed to read signing key from <issuer>/jwks: failed to parse jwks keys: <issuer>/jwks: go-jose/go-jose: invalid EC public key, wrong length for x`

If I understand you correctly you propose a flag `--jwks-signing-key-id` or `--jwks-signing-key-ids` where the id/ids would reference a subset of all of the keys exposed in the jwks endpoint. Any other key in the jwks endpoint would be ignored? 

If so yes, I think that would be a nice solution to the problem. :)

**Comment by mbilski** [comment]
I think I have a workaround for you. 

In #71 I made the callback read the signing and encryption keys from JWKs only if the JARM response is present.

I released it as v1.10.1.

Let me know if it works for you.
