### ISSUE TITLE
Add `acr_values` flag to pass to `/authorize` call

### ISSUE THREAD

**Issue by timsearle** [cloudentity/oauth2c#72]
Currently it's not possible to pass arbitrary `acr_values` as a query parameter to the `/authorize` call. Can a `-- acr_values` flag be added?

cc @piotrek-janus

**Comment by ikawalec** [comment]
Hi @timsearle 

thanks for reporting this. I've opened a PR.

**Comment by ikawalec** [comment]
@timsearle FYI this change as been released as https://github.com/cloudentity/oauth2c/releases/tag/v1.11.0

**Comment by timsearle** [comment]
Thanks a lot!
