### ISSUE TITLE
Webserver for callback refuses connection

### ISSUE THREAD

**Issue by Nimamoh** [cloudentity/oauth2c#83]
Hello,

I just installed the tool using this command

```
curl -sSfL https://raw.githubusercontent.com/cloudentity/oauth2c/master/install.sh | \
              sudo sh -s -- -b /usr/local/bin latest
```

I successfully started the tool. However, the local webserver refuses connection. When asked to open the URL, callback endpoint doesn't work. telneting to it indicates a refused connection:

```
$ telnet localhost 9876
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
```

**Comment by mbilski** [comment]
Hello,

Does it mean it is waiting for a callback forever?

```sh
 ▀ Waiting for callback. Go to the browser to authenticate... (5s)
```

?

What system are you using? Could a firewall block this port?

**Comment by felixscheinost** [comment]
I have the same issue. Reloading the page in the browser helps. Seems like the webserver for receiving the callback isn't up yet?
